name = "Calm North"
author = "Ozoku"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c3fc5878794d9e9a447e1179fc0edbcc919135e8bb2c79c7846c7d6e8eefd01"

[versions]
forge = "40.1.53"
minecraft = "1.18.2"
