name = "Calm North"
author = "Ozoku"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f080217e75148f09a666f6c28fe03b8bee040e719c19a2b2de35560272faded7"

[versions]
forge = "40.1.41"
minecraft = "1.18.2"
