name = "Calm North"
author = "Ozoku"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b573f69a5bcd249c5338ac7a1c917526036f113573467911ab40d60ee97f9c9"

[versions]
forge = "40.1.41"
minecraft = "1.18.2"
