name = "Calm North"
author = "Ozoku"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "321d335807e9768605a735be8f37527d8c3607ed869b9b1ffc31483fcb8d09f4"

[versions]
forge = "40.1.41"
minecraft = "1.18.2"
